server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://39.98.55.75:3306/www_rrthb_com_xin?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: c6f0cb2579f40794
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 39.98.55.75
    port: 6379
    password: 123456
    database: 6
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml

    
virtualFileDepositPath: /api/image/**
realityFileDepositPath: D:\xinFiles\ #结束必须要带/
