server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/www_rrthb_com_xin?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: c6f0cb2579f40794
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 6
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml

# 微信小程序的证书
wxKeyPath: /www/wwwroot/www_rrthb_com_xin/certificate/apiclient_cert.p12
wxPrivateCertPath: /www/wwwroot/www_rrthb_com_xin/certificate/apiclient_cert.pem
wxPrivateKeyPath: /www/wwwroot/www_rrthb_com_xin/certificate/apiclient_key.pem

# 文件上传时用到的路径
virtualFileDepositPath: /api/image/**
realityFileDepositPath: /www/wwwroot/www_rrthb_com_xin/resources/ #结束必须要带/