spring:
  profiles:
    active: prod
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

wxpay:
  mchId: "1666131252"
  appId: "wx2b213ad5e5c4c2a8"
  appSecret: "72b0ab089db22cc3c9a8e2fee3a5835a"
  mchKey: "134679"
  apiV3Key: "abcde12345abcde12345abcde12345ab"
  certSerialNo: "7761F8E867C2B0EC4931E46CD59A49F6B6C9AB27"
  wxKeyPath: "/www/wwwroot/www_rrthb_com_xin/certificate/apiclient_cert.p12"
  wxPrivateCertPath: "/www/wwwroot/www_rrthb_com_xin/certificate/apiclient_cert.pem"
  wxPrivateKeyPath: "/www/wwwroot/www_rrthb_com_xin/certificate/apiclient_key.pem"

weixin:
  pay:
    appid: wx2b213ad5e5c4c2a8
    mchid: 1666131252
    secret: 861b1c6e6e1be29cb4c19469d82e8d9b
    notifyurl: 支付回调地址
